### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by mayorquin** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#117]
Hello,

I receive a body containing 3 files, but I get the following error "The index was outside the bounds of the array":

The body is like this:
```
-----------------------------7daf10c20d06
Content-Disposition: form-data; name="mnpr.xml"; filename="mnpr.xml"
Content-Type: text/xml
Content-Length: 2328

...

-----------------------------7daf10c20d06
Content-Disposition: form-data; name="detectionPicture"; filename="detectionPicture.jpg"
Content-Type: image/jpeg
Content-Length: 315552

...

�UN3�@Gb8�E���=�)7('�䃷<zSK�.x�R)��-----------------------------7daf10c20d06
Content-Disposition: form-data; name="licensePlatePicture"; filename="licensePlatePicture.jpg"
Content-Type: image/jpeg
Content-Length: 13296

...

^�>����v^������-----------------------------7daf10c20d06--
```

I think the error is because the third boundary  is on the same line as the end of the second file but I don't know how to resolve it... I  tried  adding the boundary in the parser but got the following error:

Could not find expected boundary

`
var parser = new StreamingMultipartFormDataParser(result, boundary: "-----------------------------7daf10c20d06");
`
and

`
var parser = new StreamingMultipartFormDataParser(result, boundary: "7daf10c20d06");
`
Or I don't know if the problem is the encoding:

![encoding](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/assets/25123298/fa53cce8-84ca-4d1a-9803-0dbdebb884bb)

The mnpr.xml and detectPicture.jpg files download successfully

**Comment by Jericho** [comment]
I haven't investigated but I am almost certain that the issue is indeed related to the lack of line feed between the end of the data and the boundary.

My gut feeling is that this is not standard and probably violates the RFC. I need to double check whether it is acceptable to omit the line feed like in your scenario.

Do you know how this data was generated?

**Comment by mayorquin** [comment]
Thank you very much for your quick response,

The data is generated using an API of a license plate recognition camera, basically I call it manually to identify the plates and take photographs of the vehicle.

This is the documentation:

[Documentation](https://tpp.hikvision.com/wiki/isapi/anpr/GUID-2533DD50-E301-4647-8C8A-A11368111B3F.html)

From C# I do it using HttpClient

**Comment by Jericho** [comment]
I confirm that this exception is caused by the missing line feed. I was able to reproduce the problem by attempting to parse the data you provided (thanks for proactively providing this data; it made it so much easier for me to understand the situation and reproduce the problem) and I was able to manually add the missing line feed (for testing purposes) to prove that we can successfully parse this payload when it follows the expected format. Now the question is: is this a valid payload that we should be able to parse or is the data simply invalid.

I hadn't read the [RFC regarding multi-part data](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html) in a long time so, to refresh my memory, I reviewed it this morning. I paid particular attention to "The common syntax" section (I highlighted the sentence important to the situation we are investigating):
![image](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/assets/112710/3cbd53ce-c2c7-49d6-a34b-5580bd9a464e)

The critical part is the word "entirely". This means that other than the two hyphens and the arbitrary value (which is `---------------------------7daf10c20d06` in the sample you provided), nothing else should be on the same line as the boundary. This leads me to conclude that the data you are receiving from the 3rd party is malformed and does not respect the RFC regarding multi-part data.

Have you contacted the 3rd party who provides you this data to let them know that they are generating data that seems quite unusual? Even the samples in the documentation you referenced show that there should be a line feed between data and the boundary marker as you can see in this screenshot;
![image](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/assets/112710/63a5cf65-2dab-4733-89d6-d9830aafa8f8)

**Comment by mayorquin** [comment]
Thanks for your answer,

Yes I am trying to contact the supplier, to see if there is anything they can do, but I think it will take some time, since from what I have seen their firmware updates are not very frequent.

Is there any workaround I can do at the moment to be able to download the files correctly?

I tried to convert the method's response to a string and put the missing spaces in it, and then I converted the string back to a stream and used the parser, and I no longer got an error, the XML file was downloaded correctly and the images were also downloaded but apparently they are corrupted since they cannot be opened, I think the encoding is lost when I convert the string to stream

**Comment by Jericho** [comment]
If you think the issue is related to reading/converting/writing the string content, you should consider avoiding conversion and manipulate the binary content. I'm sure if you do a google search on "Replacing content of binary stream" you'll find many article that can help you.
