### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by oleg-km** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#56]
In the stream 4 files, the assembly sees only the first two
[oleg3.txt](https://github.com/Vodurden/Http-Multipart-Data-Parser/files/838075/oleg3.txt)

**Comment by oleg-km** [comment]
file MultipartFormDataParser.cs

211:                     if (Files.Count == 0 || name != Files[Files.Count - 1].Name || fileName != Files[Files.Count - 1].FileName)

**Comment by roggmaeh** [comment]
same problem, thanks oleg-km

**Comment by gattrill** [comment]
I had this issue (files being split) and oleg-km's fix worked fine.

**Comment by Jericho** [comment]
I know this is a old issue that was raised 3 years ago but I just want to let everyone know that the source of this problem was that multiple files had the same `name` and the parser used this value in an effort to uniquely identify each file. This problem was [recently resolved](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/releases/tag/4.0.0) and the name is no longer used by the parser to uniquely identify each file.
