### ISSUE TITLE
Support for dotnet core 1.0 (i.e. AWS Lambda)

### ISSUE THREAD

**Issue by mlhpdx** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#60]
It would be great to have a lightweight form data parser like this for use in AWS Lambda, which only supports dotnet core 1.0 at the moment (though that's likely to change soon).  It looks like you can do this by changing the .Net Standard build to use 1.6.0 instead of 1.6.1 (yep, it matters).  I did this locally, and it seems to work fine.  Not sure if this justifies a pull request or not.

`<NetStandardImplicitPackageVersion Condition=" '$(TargetFramework)' == 'netstandard1.3' ">1.6.0</NetStandardImplicitPackageVersion>`

**Comment by Jericho** [comment]
I realize this question was asked almost 2 years ago and wasn't addressed but I have recently taken over stewardship of this project and doing my best to go through old issues.

I see that [AWS Lambda now supports .NET Core 2.1](https://aws.amazon.com/about-aws/whats-new/2018/06/lambda-supports-dotnetcore-twopointone/) and .NET Core 2.0 is now supported by HttpMultipartParser [since version 3.0.0](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/releases/tag/3.0.0). Therefore I assume this issue can be closed.
