### ISSUE TITLE
unable to upload more than one images

### ISSUE THREAD

**Issue by shahidsalamkhan** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#63]
Hi,

while uploading one image i am able to get it, but when i upload more than images the parser object displays file count 1 only.

looking for the solution.

**Comment by Jericho** [comment]
This sounds very similar to #81, #59 and maybe also #65. I recommend upgrading to latest nuget package because an issue was resolved that caused files with same name (or blank name) to be combined into a single file.

Let me know if upgrading to the latest version resolves the issue you experienced.

**Comment by Jericho** [comment]
I am going to assume the latest release resolved this issue but feel free to comment and reopen this issue if you find that it's not the case.
