### ISSUE TITLE
Is this project still maintained and how can we make a contribution?

### ISSUE THREAD

**Issue by artcrespo** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#79]
I'm asking because I saw that they are many the issues that are still open and one pull-requests since 2018. 

Thanks!

**Comment by Jericho** [comment]
I took over this project a few months ago and since them I released two new versions. So I would say this project is indeed still maintained.

All contributions are welcome and appreciated. I have already added a note to some of the old issues that have been lingering for months (years in some cases) but feel free to help resolve the ones that are still open.
