### ISSUE TITLE
Pass dictionary to FileHandler

### ISSUE THREAD

**Issue by DamianMehers** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#85]
In my case (and perhaps this is out of the ordinary) I need a header for a `FilePart` that is not one of the ones extracted from the `parameters` dictionary passed into `ParseFilePart` in [StreamingMultipartFormDataParser.ParseFilePart](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/blob/develop/Source/HttpMultipartParser/StreamingMultipartFormDataParser.cs)

``` c#
// Read the parameters
parameters.TryGetValue("name", out string name);
parameters.TryGetValue("filename", out string filename);
parameters.TryGetValue("content-type", out string contentType);
parameters.TryGetValue("content-disposition", out string contentDisposition);
```

... and subsequently passed to `FileHandler`:

``` c#
FileHandler(name, filename, contentType, contentDisposition, fullBuffer, endPos - bufferNewlineLength, partNumber++);
```

Consequently I've modified (in my own copy) `FileHandler` to just take the `Dictionary<string, string> parameters` as a parameter and not pass in `name, filename, contentType, contentDisposition`:

``` c#
FileHandler(parameters, fullBuffer, endPos - bufferNewlineLength, partNumber++);
```

This would be a breaking change, so I am not sure what to do ... are other people finding that they need a parameter that is not one of the ones that are passed?

I'm happy to submit a pull request if this change makes sense.

**Comment by Jericho** [comment]
Can you provide an example to help me understand?

**Comment by DamianMehers** [comment]
As I said, this may not be a common scenario.  The Amazon Alexa voice service sends multipart data which just has a content type and content id.

Here I added logging to the `ParseSection` method in `StreamingMultipartFormDataParser`:

```
ParseSection Parsing line: Content-ID: <Terminal_amzn1.ask.skill.48a656db-56f8-46e7-aa1e-4a5d856878c7_3bb1d60a-cb56-4e23-bb4b-86cac587c576_CloudInitiated_664250913>
ParseSection Adding 'content-id' : '<Terminal_amzn1.ask.skill.48a656db-56f8-46e7-aa1e-4a5d856878c7_3bb1d60a-cb56-4e23-bb4b-86cac587c576_CloudInitiated_664250913>'
ParseSection Reading a line
ParseSection Parsing line: Content-Type: application/octet-stream
ParseSection Adding 'content-type' : 'application/octet-stream'
ParseSection Reading a line
ParseSection Parsing line: 
ParseSection Parsing file parts ...
```
I've had to make other changes since the logic that detected "Files" didn't work in my scenario - I have massive non-file binary data parts that stream.

**Comment by Jericho** [comment]
What would be helpful would be an example of data sent by Alexa. I’m trying to understand what data you are trying to access that is not already provided to the FileHandler. Also, it would allow me to write a quick unit test to reproduce your situation.

**Comment by Jericho** [comment]
Also, I suggest you raise a separate issue to discuss the logic to determine if a section contains a file or not.

**Comment by DamianMehers** [comment]
I'll try to put together a unit test.  Fundamentally it will be have two parts: 
The first with the header:
* `Content-Type: application/json`
and json content

...and the second with headers:
* `Content-ID: <Terminal_amzn1.ask.skill.48a656db-56f8-46e7-aa1e-4a5d856878c7_147193f3-c2c0-4738-bb07-93d22c0b60e3_CloudInitiated_1518902779>`
* `Content-Type: application/octet-stream`
and binary content of very large indeterminate length (streaming). 

Additional sections may then come down over the stream.  Those are the only headers.

**Comment by Jericho** [comment]
If you give me the payload you receive, I'll take care of the unit test (feel free to truncate the binary data to make it more manageable).

Based on my understanding so far, I think it should look something like this:
```
-----------------------------41952539122868
Content-Disposition: form-data; name="myJson"

{
    jsonProperty1 : value1,
    jsonProperty2 : value2
}
-----------------------------41952539122868
Content-Disposition: form-data; name="alexa"; filename="alexa.wav"
Content-ID: <some string>
Content-Type: application/octet-stream

<... binary data ...>
-----------------------------41952539122868--
```

**Comment by DamianMehers** [comment]
Will try to capture it and send it today.  One correction: there is no content-disposition header - no name and no filename for the binary data - it is just another part.

```
-----------------------------41952539122868
Content-Type: application/json

{
    jsonProperty1 : value1,
    jsonProperty2 : value2
}
-----------------------------41952539122868
Content-ID: <some string>
Content-Type: application/octet-stream

<... binary data ...>
-----------------------------41952539122868--
```

**Comment by Jericho** [comment]
A quick observation: up until release 4.2.0, the fact that `name` and `filename` are omitted was problematic. The fact that `filename` is not present would cause the section to be treated as a regular parameter (as opposed to a file) but the `name` is required in order to identify regular parameters. Therefore you would have gotten a "Key not found" exception. See #83 for more details.

This logic was changed in release 4.3.0 so that sections without `name` and `filename` are now treated as a file (files do not require the name and filename). This change was made to accommodate mjpeg streams where each JPEG frame is sent as a file but the name and filename are omitted.

It just occurred to me that this change also benefits you because the audio stream you receive from the Alexa service does not have name and filename either and by treating it as a file it causes the content to be streamed.

**Comment by DamianMehers** [comment]
Hi Jericho,

I've decided to continue using the older version of this library from a couple of years ago that I modified extensively - the new one takes dependencies on `Microsoft.IO.RecyclableMemoryStream` and `System.Buffers`, and while they would probably be OK, because I use this library in an app that runs on many platforms (iOS, WatchOS, Android, WearOS, Mac, Windows, xBox, and Tizen) I'm hesitant in case there are platform issues.  WatchOS especially has some weirdness because of the AOT compilation to BitCode.

I really appreciate your effort with this library, and hope to return and use the latest version.

If by any chance you use the Amazon Alexa and have a smartwatch, let me know - I use Http-Multipart-Data-Parser in my "Voice in a Can" app.

**Comment by Jericho** [comment]
The two nuget packages you mentioned were added to the project in an effort to reduce memory allocation. See #77 for benchmark and before/after comparison. Since you are targeting platforms such as watches and wearables were presumably memory is quite limited, I would think you would be interested in the improved memory utilization.

By the way, I worked on drafting a version of the HttpMultipartData parser that can capture additional parameters when processing files. It's based on my understanding of your scenario so far and I was hopping to get a sample payload from you to validate that my understanding is correct. If you have some time to check it out, I published it on my MyGet feed: https://www.myget.org/feed/jericho/package/nuget/HttpMultipartParser

**Comment by Jericho** [comment]
@DamianMehers I am planning the next release of the HttpMultipartDataParser which will contain a few breaking changes and I figured it would make sense to include the functionality you and I were discussing since it would cause a breaking change to the FileHandler delegate. Would you be available to collaborate with me and test this new feature?

By the way, did you review the memory utilization benchmark data I previously mentioned? If so, did it convince you to use the latest version of HttpMultipartDataParser or are you still using your custom built version?

**Comment by DamianMehers** [comment]
> @DamianMehers I am planning the next release of the HttpMultipartDataParser which will contain a few breaking changes and I figured it would make sense to include the functionality you and I were discussing since it would cause a breaking change to the FileHandler delegate. Would you be available to collaborate with me and test this new feature?
> 
> 
> 
> By the way, did you review the memory utilization benchmark data I previously mentioned? If so, did it convince you to use the latest version of HttpMultipartDataParser or are you still using your custom built version?

I'm afraid not. I'm moving to Swift from .NET for my Apple Watch apps since Microsoft have said they won't be supporting the Apple Watch for .NET 6... so all my focus is on Swift and SwiftUI at the moment.

Sorry,

Damian

**Comment by Jericho** [comment]
Thanks for letting me know. 

Admittedly, I don't stay completely up to date with all things related to Apple Watch, but I know that the .net team is working on [supporting Apple's new chip](https://github.com/dotnet/runtime/issues/43313). I naively assumed it would also include watches, phones, pads, etc. but I'll defer to you since you are most likely more informed than me on this topic.

**Comment by DamianMehers** [comment]
It's great that they will be supporting the M1, this is the info on the Apple Watch https://github.com/xamarin/xamarin-macios/issues/8955#issuecomment-742006609
