### ISSUE TITLE
Files without filename are not recognized

### ISSUE THREAD

**Issue by bkrbtc** [Http-Multipart-Data-Parser/Http-Multipart-Data-Parser#90]
The following content ist not parsed properly:

> --d81b2c7d-6487-40a8-9d17-808479d33e45
> Content-Disposition: form-data; name="parameter1"
> Content-Type: application/json
> 
> "string value of parameter 1"
> --d81b2c7d-6487-40a8-9d17-808479d33e45
> Content-Disposition: form-data; name="myFile1"
> Content-Type: application/octet-stream
> 
> [Binary data of myFile1 goes here]

myFile1 is erroneously recognized as a parameter instead of a file, because the "filename" is missing. Parameters have only a string representation. Since the property "filename" is not mandatory(RFC 7578), the given example looks RFC compliant.

This pullrequest address the issue https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/pull/89

**Comment by Jericho** [comment]
As you point out, the RFC recommends that a filename be provided but it's not mandatory. It says the following:

> For form data that represents the content of a file, a name for the file SHOULD be supplied as well, by using a "filename" parameter

This means that relying on the presence of this property is not a reliable way of determining if a form section contains a file or not. We currently use the following heuristics to **_attempt_** to determine of a section should be considered as "file" or not:
- if the section contains 'filename', it's a file
- if the section contains neither 'filename' nor 'name', it's a file (this logic was recently added in order to [support mjpeg streams](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser/issues/83))
- otherwise, it's not a file

Your idea to add another heuristic which would look at the mimetype (if present), sounds interesting.

**Comment by bkrbtc** [comment]
Thank you. At the moment my code uses only octet stream as a default. (Can be overridden by the user). If you find a reliable list of binary (only) content-types you may can enhance the list the improve the recognition.

**Comment by bkrbtc** [comment]
@Jericho Do you have a release plan/schedule for nuget?

**Comment by Jericho** [comment]
I'm investigating why BenchmarkDotNet is causing the build to fail. The final release might be delayed but in the mean time I published a release candidate on [my MyGet feed](https://myget.org/feed/jericho/package/nuget/HttpMultipartParser/4.4.0-rc0003). If you could try it out and give me some feedback that would be appreciated.

**Comment by bkrbtc** [comment]
I tested my use case with a variation of payloads and parameters: Everything works as expected.

**Comment by Jericho** [comment]
Excellent, thank you for the feedback. I'm kinda stuck with the benchmarking issue but as soon as I figure it out, I'll publish the final version to NuGet.

Thanks again

**Comment by bkrbtc** [comment]
Thank you
